apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - fission
  selector:
    matchLabels:
      svc: agent
  endpoints:
  - targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - fission
  selector:
    matchLabels:
      svc: controller
  endpoints:
  - targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: executor-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - fission
  selector:
    matchLabels:
      svc: executor
  endpoints:
  - targetPort: 8080